# Generated by Django 4.2.23 on 2025-08-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_frais', models.CharField(max_length=100, verbose_name='Nom du frais')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('PONCTUEL', 'Ponctuel')], max_length=20, verbose_name='Périodicité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
                'ordering': ['nom_frais'],
            },
        ),
    ]
