# Generated by Django 4.2.23 on 2025-08-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la caisse')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('couleur', models.CharField(default='#3498db', help_text='Code hexadécimal de la couleur (ex: #3498db)', max_length=7, verbose_name='Couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Type de caisse',
                'verbose_name_plural': 'Types de caisses',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='typefrais',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (Ar)'),
        ),
    ]
