# Generated by Django 4.2.23 on 2025-08-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_typecaisse_alter_typefrais_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='type_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_frais', to='finance.typecaisse', verbose_name='Type de caisse'),
        ),
    ]
