# Generated by Django 4.2.23 on 2025-08-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_typefrais_type_caisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typefrais',
            name='type_caisse',
        ),
    ]
