# Generated by Django 4.2.23 on 2025-08-14 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_remove_typefrais_type_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (Ar)')),
                ('date_paiement', models.DateTimeField(verbose_name='Date de paiement')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(choices=[('ESPECE', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE', 'Paiement mobile'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (numéro de chèque, transaction, etc.)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('type_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.typecaisse', verbose_name='Type de caisse')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.typefrais', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
