# Generated by Django 4.2.23 on 2025-08-14 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
        ('academics', '0001_initial'),
        ('finance', '0006_paiement_mois'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTÉE', 'Acceptée'), ('REFUSÉE', 'Refusée'), ('CONFIRMÉE', 'Confirmée'), ('ANNULÉE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='school.schoolyear', verbose_name='Année scolaire')),
                ('classe_attribuee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_attribuees', to='academics.class', verbose_name='Classe attribuée')),
                ('classe_demandee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_inscription', to='academics.class', verbose_name='Classe demandée')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
