# Generated by Django 4.2.23 on 2025-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='frais_inscription',
            field=models.BooleanField(default=False, verbose_name="Frais d'inscription"),
        ),
    ]
