# Generated by Django 4.2.23 on 2025-08-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_typefrais_frais_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='type_inscription',
            field=models.CharField(choices=[('PASSANT', 'Passant'), ('REDOUBLANT', 'Redoublant')], default='PASSANT', max_length=20, verbose_name="Type d'inscription"),
        ),
    ]
