# Generated by Django 4.2.23 on 2025-08-12 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Administrateur'), ('teacher', 'Enseignant'), ('student', 'Élève'), ('parent', 'Parent')], default='student', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CIN / Passeport')),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf(ve)')], max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('internal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule interne')),
                ('professional_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID professionnel')),
                ('diplomas', models.TextField(blank=True, null=True, verbose_name='Diplômes et formations')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste occupé')),
                ('employment_status', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contractuel'), ('part_time', 'Temps partiel'), ('substitute', 'Remplaçant')], max_length=20, null=True, verbose_name="Statut d'emploi")),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name="Années d'expérience")),
                ('previous_positions', models.TextField(blank=True, null=True, verbose_name='Expériences professionnelles précédentes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
