# Generated by Django 4.2.23 on 2025-08-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employeur'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone professionnel'),
        ),
    ]
