# Generated by Django 4.2.23 on 2025-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf(ve)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diplomas',
            field=models.TextField(blank=True, null=True, verbose_name='Diplômes et formations'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contractuel'), ('part_time', 'Temps partiel'), ('substitute', 'Remplaçant')], max_length=20, null=True, verbose_name="Statut d'emploi"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CIN / Passeport'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='internal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule interne'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste occupé'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_positions',
            field=models.TextField(blank=True, null=True, verbose_name='Expériences professionnelles précédentes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID professionnel'),
        ),
    ]
