# Generated by Django 4.2.23 on 2025-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_employer_userprofile_number_of_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions médicales'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='École précédente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_school_address',
            field=models.TextField(blank=True, null=True, verbose_name="Adresse de l'école précédente"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'étudiant"),
        ),
    ]
