# Generated by Django 4.2.23 on 2025-08-13 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0003_userprofile_allergies_userprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('father', 'Père'), ('mother', 'Mère'), ('guardian', 'Tuteur/Tutrice'), ('stepfather', 'Beau-père'), ('stepmother', 'Belle-mère'), ('grandfather', 'Grand-père'), ('grandmother', 'Grand-mère'), ('other', 'Autre')], default='guardian', max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('has_pickup_rights', models.BooleanField(default=True, verbose_name='Droit de récupération')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation Parent-Élève',
                'verbose_name_plural': 'Relations Parent-Élève',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
