# Generated by Django 4.2.23 on 2025-08-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du chapitre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_chapters', to='academics.classsubject')),
            ],
            options={
                'verbose_name': 'Chapitre du programme',
                'verbose_name_plural': 'Chapitres du programme',
                'ordering': ['order', 'title'],
                'unique_together': {('class_subject', 'title')},
            },
        ),
    ]
