# Generated by Django 4.2.23 on 2025-08-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programchapter',
            name='subtitle',
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre du sous-titre')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='teachers.programchapter')),
            ],
            options={
                'verbose_name': 'Sous-titre',
                'verbose_name_plural': 'Sous-titres',
                'ordering': ['order', 'title'],
                'unique_together': {('chapter', 'title')},
            },
        ),
    ]
