# Generated by Django 4.2.23 on 2025-08-17 04:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
        ('teachers', '0002_remove_programchapter_subtitle_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'interrogation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name="Date de l'interrogation")),
                ('subject_pdf', models.FileField(upload_to='interrogation_subjects/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Sujet PDF')),
                ('total_points', models.PositiveIntegerField(default=20, verbose_name='Total des points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to='teachers.programchapter')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='academics.classsubject')),
            ],
            options={
                'verbose_name': 'Interrogation',
                'verbose_name_plural': 'Interrogations',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InterrogationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.FloatField(verbose_name='Points obtenus')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='teachers.interrogation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Note d'interrogation",
                'verbose_name_plural': "Notes d'interrogation",
                'unique_together': {('interrogation', 'student')},
            },
        ),
    ]
