# Generated by Django 4.2.23 on 2025-08-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teachersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_levels', to='academics.classlevel')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.teachersubject')),
            ],
            options={
                'verbose_name': "Niveau d'enseignement",
                'verbose_name_plural': "Niveaux d'enseignement",
                'unique_together': {('teacher_subject', 'class_level')},
            },
        ),
    ]
