# Generated by Django 4.2.23 on 2025-08-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, help_text='Coefficient de la matière pour le calcul de la moyenne.'),
        ),
    ]
