# Generated by Django 4.2.23 on 2025-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_schedule_timeslot_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#3498db', help_text='Code hexadécimal de la couleur (ex: #3498db)', max_length=7),
        ),
    ]
